# Generated by Django 5.0 on 2026-02-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_applicant_dob_fundapplication_youth_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_category', models.CharField(choices=[('HABARI', 'Habari na Mambo ya Sasa'), ('BURUDANI', 'Burudani'), ('ELIMU', 'Elimu na Dini'), ('SIMULCASTING', 'Simulcasting')], max_length=30)),
                ('creator_type', models.CharField(choices=[('AMATEUR', 'Amateur'), ('PROFESSIONAL', 'Professional'), ('AGGREGATOR', 'Aggregator')], max_length=20)),
                ('is_amateur', models.BooleanField(default=False)),
                ('fee_type', models.CharField(choices=[('APPLICATION', 'Application'), ('LICENCE', 'Licence')], default='APPLICATION', max_length=20)),
                ('amount_tzs', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_number', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licence', to='applicants.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
